---
- hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Adding TeamSpeak User
      user:
        name: ts3

    - name: Extract downloaded folder
      unarchive:
        src: https://files.teamspeak-services.com/releases/server/3.9.1/teamspeak3-server_linux_amd64-3.9.1.tar.bz2
        dest: /home/ts3
        remote_src: yes

    - name: Add TeamSpeak as a service

    - name: Start the TeamSpeak server

  handlers:
    - name: Start Teamspeak
      service:
        name: ts3
        state: restarted
